services:
  api:
    build: .
    image: ernest/project-tracker-api
    container_name: project-tracker-api
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/project
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

      SPRING_DATA_MONGODB_URI: mongodb://mongo:27017/auditdb
    depends_on:
      - db
      - mongo

  db:
    image: postgres:16
    container_name: project_tracker-db
    environment:
      POSTGRES_DB: project
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"


  mongo:
    image: mongo:7
    container_name: project_tracker-mongo
    ports:
      - "27017:27017"
